name: YAML Lint Check

on:
  push:
    branches:
      - main  # Modify this to match your branch name

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install yamllint
        run: |
          pip install yamllint
        # Make sure Python and pip are available in your environment.

      - name: Run yamllint
        run: |
          yamllint -c .github/yamllint.yaml .github/yamllint.yaml
        # Replace 'your-yaml-file.yaml' with the actual path to your YAML file.
      - name: Install jsonlint
        run: |
          npm install -g jsonlint
        # Make sure Node.js and npm are available in your environment.

      - name: Validate YAML against JSON Schema
        run: |
          jsonlint -q -c .github/yamllint.schema.yaml .github/yamllint.yaml
        continue-on-error: true  
         
